### ISSUE TITLE
Поменять картинку в организации

### ISSUE THREAD

**Issue by blrB** [ostis-apps/ostis-ann#1]
Поменять картинку в организации, а то в текущей какой-то пискельный дизайн. Кратинку в нормальном разрешении приложил

https://user-images.githubusercontent.com/9513452/38829714-ac5e1196-41c2-11e8-8075-3c249fdefd66.png

![ostis](https://user-images.githubusercontent.com/9513452/38829714-ac5e1196-41c2-11e8-8075-3c249fdefd66.png)

**Comment by KovalM** [comment]
done
